FunTextMVC/Models/AppUser.cs
namespace FunTextMVC.Models;

public class AppUser : IdentityUser
{
    [StringLength(100)]
    [MaxLength(100)]
    [Required]
    public string? Name { get; set; }
}

FunTextMVC/Models/ErrorViewModel.cs
namespace FunTextMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

FunTextMVC/ViewModels/ChangePasswordVM.cs
namespace FunTextMVC.ViewModels;

public class ChangePasswordVM
{
    [Required]
    [DataType(DataType.Password)]
    [Display(Name = "Current password")]
    public string? OldPassword { get; set; }

    [Required]
    [DataType(DataType.Password)]
    [Display(Name = "New password")]
    public string? NewPassword { get; set; }

    [Compare("NewPassword", ErrorMessage = "Passwords don't match.")]
    [Display(Name = "Confirm Password")]
    [DataType(DataType.Password)]
    public string? ConfirmPassword { get; set; }
}

FunTextMVC/ViewModels/LoginVM.cs
namespace FunTextMVC.ViewModels;

public class LoginVM
{
    [Required(ErrorMessage = "Username is required.")]
    public string? Username { get; set; }

    [Required(ErrorMessage = "Password is required.")]
    [DataType(DataType.Password)]
    public string? Password { get; set; }

    [Display(Name = "Remember Me")]
    public bool RememberMe { get; set; }
}

FunTextMVC/ViewModels/RegisterVM.cs
namespace FunTextMVC.ViewModels;

public class RegisterVM
{
    [Required]
    public string? Name { get; set; }

    [Required]
    public string? UserName { get; set; }

    [DataType(DataType.EmailAddress)]
    public string? Email { get; set; }

    [Required]
    [DataType(DataType.Password)]
    public string? Password { get; set; }

    [Compare("Password", ErrorMessage = "Passwords don't match.")]
    [Display(Name = "Confirm Password")]
    [DataType(DataType.Password)]
    public string? ConfirmPassword { get; set; }

}

FunTextMVC/Controllers/AccountController.cs
using FunTextMVC.Models;
using FunTextMVC.ViewModels;

namespace FunTextMVC.Controllers;

//Controller handles User Authentication
public class AccountController(SignInManager<AppUser> signInManager, UserManager<AppUser> userManager) : Controller
{
    public IActionResult Login(string? returnUrl = null)
    {
        ViewData["ReturnUrl"] = returnUrl;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginVM model, string? returnUrl = null)
    {
        ViewData["ReturnUrl"] = returnUrl;
        if (ModelState.IsValid)
        {
            //login
            var loginResult = await signInManager.PasswordSignInAsync(model.Username!, model.Password!, model.RememberMe, false);

            if (loginResult.Succeeded)
            {
                TempData["Success"] = "Login successful.";
                return RedirectToLocal(returnUrl);
            }

            ModelState.AddModelError("", "Invalid login attempt");
        }
        return View(model);
    }

    [Authorize]
    public IActionResult Register(string? returnUrl = null)
    {
        ViewData["ReturnUrl"] = returnUrl;
        return View();
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> Register(RegisterVM model, string? returnUrl = null)
    {
        ViewData["ReturnUrl"] = returnUrl;
        if (ModelState.IsValid)
        {
            AppUser user = new()
            {
                Name = model.Name,
                UserName = model.UserName,
                Email = model.Email,
            };

            var createUserResult = await userManager.CreateAsync(user, model.Password!);

            if (createUserResult.Succeeded)
            {
                TempData["Success"] = "User created successfully.";
                return View();
            }
            foreach (var error in createUserResult.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
        return View(model);
    }

    [Authorize]
    public IActionResult ChangePassword(string? returnUrl = null)
    {
        ViewData["ReturnUrl"] = returnUrl;
        return View();
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> ChangePassword(ChangePasswordVM model, string? returnUrl = null)
    {
        ViewData["ReturnUrl"] = returnUrl;
        if (ModelState.IsValid)
        {
            var user = await userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userManager.GetUserId(User)}'.");
            }

            var changePasswordResult = await userManager.ChangePasswordAsync(user, model.OldPassword!, model.NewPassword!);
            if (changePasswordResult.Succeeded)
            {
                TempData["Success"] = "Your password has been changed.";
                await signInManager.RefreshSignInAsync(user);
                return View();
            }
            foreach (var error in changePasswordResult.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        return View(model);
    }

    public async Task<IActionResult> Logout()
    {
        await signInManager.SignOutAsync();
        return RedirectToAction("Index", "Home");
    }

    private IActionResult RedirectToLocal(string? returnUrl)
    {
        return !string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl)
            ? Redirect(returnUrl)
            : RedirectToAction(nameof(HomeController.Index), "Home");
    }
}

FunTextMVC/Controllers/HistoryController.cs
namespace FunTextMVC.Controllers;

[Authorize]
public class HistoryController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

FunTextMVC/Controllers/HomeController.cs
namespace FunTextMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

FunTextMVC/Controllers/TranslatorController.cs
using ILogger = Microsoft.Extensions.Logging.ILogger;

namespace FunTextMVC.Controllers;

[Authorize]
public class TranslatorController : Controller
{
    private readonly ILogger logger;
    private readonly ITranslatorsData translatorsData;

    public TranslatorController(ILogger<TranslatorController> logger, ITranslatorsData translatorsData)
    {
        this.logger = logger;
        this.translatorsData = translatorsData;
    }

    public async Task<IActionResult> Index()
    {
        try
        {
            var translators = (await translatorsData.Get()).ToList();
            return View(translators);
        }
        catch (Exception ex)
        {
            TempData["Error"] = ex.Message;
            return View();
        }
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(TranslatorModel model)
    {
        if (ModelState.IsValid)
        {
            try
            {
                await translatorsData.Insert(model);
                TempData["Success"] = "Translator added successfully";
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
            }
        }
        return View();
    }

    public async Task<IActionResult> Detail(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }

        var translator = (await translatorsData.Get(id)).FirstOrDefault();
        if (translator == null)
        {
            return NotFound();
        }

        return View(translator);
    }

    [HttpPost]
    public async Task<IActionResult> Detail(TranslatorModel model)
    {
        if (ModelState.IsValid)
        {
            try
            {
                await translatorsData.Update(model);
                TempData["Success"] = "Translator updated successfully";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
            }
        }
        return View();
    }
}

FunTextMVC/Views/History/Index.cshtml
@using FunTextMVC.Views.BlazorComponents
@{
    ViewData["Title"] = "History";
}

<div class="container">
    <div class="card card-outline-info shadow-lg mt-4 p-2">
        <div class="card-header bg-secondary bg-gradient py-3">
            <div class="row">
                <div class="col-12 text-center">
                    <h2>Translation History</h2>

                </div>
            </div>
        </div>

        <div class="card-body h-100  col-12">

            @* Gets and renders the blazor component (QuickGrid/DataTable) for display in view. *@
            @(await Html.RenderComponentAsync<HistoryComponent>(RenderMode.Server))

        </div>
    </div>
</div>

FunTextMVC/Views/Home/Index.cshtml
@using FunTextMVC.Views.BlazorComponents
@{
    ViewData["Title"] = "Translate";
}

<partial name="_Notification" />

<div class="m-5">

    <div>
        <div class="pt-5 text-center">
            <h1 class="display-1 text-info-emphasis">Welcome To Fun Text</h1>
            <h5 class="display-6 text-capitalize text-success-emphasis fw-semibold">Translations made fun.</h5>
        </div>

        <div>

            @* Gets and renders the blazor component for display in view. *@
            @(await Html.RenderComponentAsync<TranslateComponent>(RenderMode.Server))

        </div>

    </div>

</div>

FunTextMVC/Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fun Text - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/FunTextMVC.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid ms-5 me-5">
                <a class="navbar-brand ms-5" asp-area="" asp-controller="Home" asp-action="Index">Fun Text</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Translator" asp-action="Index">Translators</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="History" asp-action="Index">History</a>
                            </li>
                        }
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Fun Text
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @* Blazor script *@
    <script src="_framework/blazor.server.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FunTextMVC/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

FunTextMVC/Views/Translator/Create.cshtml
@model TranslatorModel
@{
    ViewData["Title"] = "New Translator";
}

<div class="container">
    <form method="post">
        <div class="card card-outline-info shadow-lg mt-4 p-2">

            <div class="card-header bg-secondary bg-gradient mt-0 py-3">
                <div class="row">
                    <div class="col-12 text-center">
                        <h2>New Translator</h2>

                    </div>
                </div>
            </div>

            <div class="card-body p-4">
                <div class="border p-3">
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Name" class="form-control border-0 shadow" />
                        <label asp-for="Name" class="ms-2">Name</label>
                        <span asp-validation-for="Name" class="text-danger" />
                    </div>

                    <div class="form-floating py-2 col-12">
                        <input asp-for="BaseUrl" class="form-control border-0 shadow" />
                        <label asp-for="BaseUrl" class="ms-2">Base Url</label>
                        <span asp-validation-for="BaseUrl" class="text-danger" />
                    </div>

                    <div class="form-floating py-2 col-12">
                        <input asp-for="ApiKey" class="form-control border-0 shadow" />
                        <label asp-for="ApiKey" class="ms-2">Api Key</label>
                    </div>
                </div>
            </div>

            <div class="card-footer row ms-2 me-2">
                <div class="col-6 col-md-3">
                    <input asp-action="Create" type="submit" class="btn btn-secondary form-control" value="Save" />
                </div>

                <div class="col-6 col-md-3">
                    <a asp-controller="Translator" asp-action="Index" class="btn btn-outline-primary border form-control">
                        Back to List
                    </a>
                </div>
            </div>

        </div>
    </form>
</div>

FunTextMVC/Views/Translator/Detail.cshtml
@model TranslatorModel
@{
    ViewData["Title"] = "Edit Translator";
}

<div class="container">
    <form method="post">
        <div class="card card-outline-info shadow-lg mt-4 p-2">

            <div class="card-header bg-secondary bg-gradient mt-0 py-3">
                <div class="row">
                    <div class="col-12 text-center">
                        <h2>Edit Translator</h2>

                    </div>
                </div>
            </div>

            <div class="card-body p-4">
                <div class="border p-3">
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Name" class="form-control border-0 shadow" />
                        <label asp-for="Name" class="ms-2">Name</label>
                        <span asp-validation-for="Name" class="text-danger" />
                    </div>

                    <div class="form-floating py-2 col-12">
                        <input asp-for="BaseUrl" class="form-control border-0 shadow" />
                        <label asp-for="BaseUrl" class="ms-2">Base Url</label>
                        <span asp-validation-for="BaseUrl" class="text-danger" />
                    </div>

                    <div class="form-floating py-2 col-12">
                        <input asp-for="ApiKey" class="form-control border-0 shadow" />
                        <label asp-for="ApiKey" class="ms-2">Api Key</label>
                    </div>
                </div>
            </div>

            <div class="card-footer row ms-2 me-2">
                <div class="col-6 col-md-3">
                    <input asp-action="Detail" type="submit" class="btn btn-secondary form-control" value="Save" />
                </div>

                <div class="col-6 col-md-3">
                    <a asp-controller="Translator" asp-action="Index" class="btn btn-outline-primary border form-control">
                        Back to List
                    </a>
                </div>
            </div>

        </div>
        </form>
</div>

FunTextMVC/Views/Translator/Index.cshtml
@model List<TranslatorModel>
@{
    ViewData["Title"] = "Translators";
}

<partial name="_Notification" />

<div class="container">
    <div class="card card-outline-info shadow-lg mt-4 p-2">
        <div class="card-header bg-secondary bg-gradient mt-0 py-3">
            <div class="row">
                <div class="col-12 text-center">
                    <h2>Translators</h2>

                </div>
            </div>
        </div>

        <div class="mt-3">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Base Url</th>
                        <th>Api Key</th>
                    </tr>
                </thead>

                <tbody>
                    @if (Model != null)
                    {
                        foreach (var t in Model)
                        {
                            <tr>
                                <td>@t.Name</td>
                                <td>@t.BaseUrl</td>
                                <td>@t.ApiKey</td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <a asp-controller="Translator" asp-action="Detail" asp-route-id="@t.Id" class="btn btn-primary">
                                            <i class="bi bi-pencil-square"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        }

                    }

                </tbody>
            </table>
        </div>

        <div>
            <a asp-controller="Translator" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle">
                    New
                </i>
            </a>
        </div>
    </div>
</div>